#!/usr/bin/env bash
#title           :uninstall
#description     :This script will uninstall HADES system from computer.
#author		     :horovtom, keombre
#version         :0.1
#usage		     :bash uninstall [-a] [-h]
#notes           :-a switch will delete all local user settings
#=============================================================================

targetDir="/opt/hades"

if [ "$EUID" -ne 0 ] ; then
    echo "ERROR: Please run this script as root!!"
    exit -10
fi

function deinstall() {

    #Remove scripts:
    sudo systemctl disable hades
    sudo systemctl stop hades
    sudo rm -f /etc/systemd/system/hades.service
    sudo rm -f /etc/systemd/system/hades.timer
    sudo systemctl daemon-reload

    #Remove command:
    sudo rm -f /usr/bin/hades
    sudo rm -f /usr/bin/gpjp-hades
    
    #Remove user
    deluser --quiet hades

    echo "DONE!"
    exit 0
}

function removeAll() {
    echo "All right, let's do it!"
    sudo rm -rf $targetDir
    deinstall
}

function removePart() {
    echo "All right, let's do it!"
    sudo find $targetDir/ -not -name 'localSettings.sh' -type f -exec rm {} +
    deinstall
}

if [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then
    echo "This script will delete HADES system from this computer. Use switch -a to delete all the files, if not specified, script will leave out local settings."
    exit 0
fi

if [[ "$1" == "-a" ]]
then
    printf "This will remove Hades Completly! Proceed? [y/N]: "
    read -n 1 -r
    echo 
    if [[ $REPLY =~ (^[Yy]$) ]]
    then
        removeAll
    fi
elif [[ $# -eq 0 ]]
then
    printf "This will remove Hades. Proceed? [y/N]: "
    read -n 1 -r
    echo 
    if [[ $REPLY =~ (^[Yy]$) ]]
    then
        printf "Preserve configs? [Y/n]: "
        read -n 1 -r
        echo 
        if [[ $REPLY =~ (^[Yy]$|^$) ]]
        then
            removePart
        else
            removeAll
        fi
    fi
else
    echo "Unrecognized parameters! Use -h for help."
    exit -1
fi

echo "Cancelled"
exit 1
