#!/usr/bin/env bash
#title           :main
#description     :This script will be executed on boot-sequence and update startup-execute from git repository, then run it
#author		     :horovtom, keombre
#version         :0.2
#notes           :This script will take existing gpjp-config clone from gpjp-startup-updater.sh
#==============================================================================

targetDir="/opt/hades" # probably not needed, since systemd puts us here already 
updateDir=$targetDir/Remote

function loadConfig() {
    if [[ ! -f $1 ]]
    then
        echo "Config not found in "$targetDir/$1
        exit -1
    else
        . $1
    fi
}

#check connectivity
if nc -z github.com 80 >/dev/null 2>&1
then

    # get configs (since we will be sourcing all other scripts, we need to do this only once)
    loadConfig hades.conf
    loadConfig local.conf

    if [[ ! -d $updateDir/.git ]]
    then
        echo "Repository not found in: "$updateDir" Quitting."
        exit -1
    fi

    # update updater
    if cmp $updateDir/run/updater ./updater -s
    then
        echo "updater up to date"
    else
        echo "updating updater"
        cp -f $updateDir/run/updater .
        echo "updater updated, quitting"
        exit 0
    fi

    echo "Update finished, cleanup..."
    rm -rf Remote

    #Run startup parse script:
    echo "Running parse script"
    . parse # sourcing to preserve environment (probably solves that sleep mess down below)

    echo "Parse script returned: "$?
    #FIXME: Wait for all async calls (Shouldn't be needed!)
    sleep 10

else
    echo "Github unreachable. Network down?"
fi