#!/usr/bin/env bash
#title           :update
#description     :Check git for changes, if present apply them localy
#author		     :keombre
#version         :0.1
#notes           :
#==============================================================================

repository="git://github.com/gpjp-hades/Scripts.git"

updateDir="Remote"
branch="systemd"

function updateFile() {
    if [[ $2 ]]
    then
        name=$2
    else
        name=$1
    fi

    if cmp $updateDir/$1 $name -s
    then
        echo $name" up to date"
    else
        echo "updating "$name
        cp -f $updateDir/$1 $name
    fi
}

if nc -z github.com 80 >/dev/null 2>&1
then
    # ensure privliegies
    sudo chown -R hades:hades .
    sudo chmod -R 700 .

    # ensure git and curl
    if ! dpkg -s git curl jq >/dev/null 2>&1
    then
        echo "Git, curl or jq not found, fixing: "
        sudo apt-get install git curl jq -y
    fi

    # get latest commit
    commit=$(git ls-remote $repository $branch | awk '{print $1;}')

    # update if necessary
    if [[ ! -f "commit.ver" || "$commit" != $(< commit.ver) ]]
    then

        if [[ -d $updateDir ]] && [[ ! -d $updateDir/.git ]]
        then
            rm -r $updateDir
        fi
        
        if [[ -d $updateDir/.git ]]
        then
            git -C $updateDir pull
        else
            git clone -b $branch $repository $updateDir
        fi

        if [[ ! -d $updateDir/.git ]]
        then
            echo "Git failed, quiting"
            exit -4
        fi

        updateFile run/main main
        updateFile hades.conf
        
        updateFile /service/hades.service /etc/systemd/system/hades.service
        updateFile /service/hades.timer /etc/systemd/system/hades.timer

        updateFile lib/parse parse
        updateFile lib/run run

        # update command (probably not needed, since we have service)
        if cmp $updateDir/run/hades /usr/bin/hades -s
        then
            echo "command up to date"
        else
            echo "updating command"
            cp $updateDir/run/hades /usr/bin/hades
            chmod +x /usr/bin/hades
            rm -f /usr/bin/gpjp-hades
            ln /usr/bin/hades /usr/bin/gpjp-hades
        fi

        # update local repo info
        echo $commit > commit.ver
        echo "commit updated, update finished"
    else
        echo "up to date"
    fi
else
    echo "Github unreachable. Network down?"
fi
